-- Create commands table
CREATE TABLE IF NOT EXISTS commands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  command_type TEXT NOT NULL, -- 'start_listen', 'stop_listen'
  status TEXT DEFAULT 'pending', -- 'pending', 'active', 'completed'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Realtime for the commands table
ALTER TABLE commands REPLICA IDENTITY FULL;

-- Note: In Supabase dashboard, you must go to Database -> Replication -> supabase_realtime 
-- and ensure the 'commands' table is included.

-- 3. Create Recordings Table
CREATE TABLE IF NOT EXISTS public.recordings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    duration INTEGER, -- in seconds
    user_id UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable RLS
ALTER TABLE public.commands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recordings ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies
-- Allow authenticated users to insert commands
CREATE POLICY "Users can create commands" 
ON public.commands FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- Allow authenticated users to view commands
CREATE POLICY "Users can view commands" 
ON public.commands FOR SELECT 
TO authenticated 
USING (true);

-- Allow authenticated users to view their own recordings
CREATE POLICY "Users can view their recordings" 
ON public.recordings FOR SELECT 
TO authenticated 
USING (auth.uid() = user_id);

-- Allow authenticated users to insert recordings
CREATE POLICY "Users can insert recordings" 
ON public.recordings FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

-- 6. Enable Realtime
-- Ensure these tables are in the supabase_realtime publication
-- ALTER PUBLICATION supabase_realtime ADD TABLE commands;
-- ALTER PUBLICATION supabase_realtime ADD TABLE recordings;
